version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      default:
        ipv4_address: 192.16.0.39

  redis:
    build: redis/
    container_name: redis
    volumes:
      - ./redis/config:/usr/local/etc/redis
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 192.16.0.37

  logstash-shipper:
    build: logstash-shipper/
    container_name: logstash-shipper
    command: -f /etc/logstash/conf.d/
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    networks:
      default:
        ipv4_address: 192.16.0.38

  logstash-indexer:
    build: logstash-indexer/
    container_name: logstash-indexer
    command: -f /etc/logstash/conf.d/
    networks:
      default:
        ipv4_address: 192.16.0.36

  kibana:
    build: kibana/
    container_name: kibana
    ports:
      - "5601:5601"


networks:
  default:
    external:
      name: elk

