version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  logstash:
    build: logstash/
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "12201:12201"
      - "12201:12201/udp"
    networks:
      default:
        ipv4_address: 192.16.0.38

  kibana:
    build: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    logging:
      driver: gelf
      options:
        gelf-address: udp://192.16.0.38:12201
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200


networks:
  default:
    external:
      name: elk

